name: counting_company
channels:
- conda-forge
- defaults
dependencies:
- attrs=17.2.0=py35_0
- backports.weakref=1.0rc1=py35_0
- blas=1.1=openblas
- bleach=1.5.0=py35_0
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- cairo=1.14.6=4
- certifi=2017.7.27.1=py35_0
- cycler=0.10.0=py35_0
- dbus=1.10.22=0
- django=1.11.5=py_0
- expat=2.2.1=0
- ffmpeg=3.2.4=1
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=2
- h5py=2.7.1=py35_1
- harfbuzz=1.3.4=2
- hdf5=1.8.18=1
- html5lib=0.9999999=py35_0
- hypothesis=3.23.0=py35_0
- icu=58.1=1
- inflection=0.3.1=py35_0
- jasper=1.900.1=4
- jpeg=9b=1
- keras=2.0.6=py35_0
- libffi=3.2.1=3
- libgpuarray=0.7.3=0
- libiconv=1.14=4
- libpng=1.6.28=1
- libtiff=4.0.7=0
- libwebp=0.5.2=7
- libxcb=1.12=1
- libxml2=2.9.5=0
- mako=1.0.7=py35_0
- markdown=2.6.9=py35_0
- markupsafe=1.0=py35_0
- matplotlib=2.0.2=py35_2
- mock=2.0.0=py35_0
- ncurses=5.9=10
- numpy=1.13.1=py35_blas_openblas_200
- olefile=0.44=py35_0
- openblas=0.2.19=2
- opencv=3.3.0=py35_blas_openblas_200
- openssl=1.0.2l=0
- pbr=3.1.1=py35_0
- pcre=8.39=0
- pillow=4.2.1=py35_1
- pip=10.0.1=py35_0
- pixman=0.34.0=0
- protobuf=3.4.0=py35_0
- pygpu=0.7.3=np113py35_0
- pympler=0.5=py35_0
- pyparsing=2.2.0=py35_0
- pyqt=5.6.0=py35_4
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- pytz=2017.2=py35_0
- pyyaml=3.12=py35_1
- qt=5.6.2=3
- readline=6.2=0
- scikit-learn=0.19.0=py35_blas_openblas_201
- scipy=0.19.1=py35_blas_openblas_202
- setuptools=36.3.0=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- sqlite=3.13.0=1
- tensorflow=1.3.0=py35_0
- theano=0.9.0=py35_1
- tk=8.5.19=2
- tornado=4.5.2=py35_0
- webencodings=0.5=py35_0
- werkzeug=0.12.2=py_1
- wheel=0.30.0=py_1
- x264=20131217=3
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- zope=1.0=py35_0
- zope.interface=4.4.2=py35_0
- pip:
  - coremltools==0.8
  - grpcio==1.6.0
  - bugsnag==3.2.0
prefix: /opt/conda/envs/counting_company
