apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: mlv1
          image: us.gcr.io/counting-company-production/ml
          args: [ "source activate counting_company && KERAS_BACKEND=tensorflow exec python -u manage.py rpcserver --mlversion 1" ]
          envFrom:
            - secretRef:
                name: ml-environment
        - name: mlv2
          image: us.gcr.io/counting-company-production/ml
          args: [ "source activate counting_company && KERAS_BACKEND=tensorflow exec python -u manage.py rpcserver --mlversion 2" ]
          envFrom:
            - secretRef:
                name: ml-environment
